apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.namePrefix }}-apps-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "iot-homeguard-apps.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}
  MONGO_PASSWORD: {{ .Values.secrets.mongoPassword | quote }}
  {{- if .Values.secrets.redisPassword }}
  REDIS_PASSWORD: {{ .Values.secrets.redisPassword | quote }}
  {{- end }}
  {{- if .Values.agenticAi.geminiApiKey }}
  GEMINI_TEXT_API_KEY: {{ .Values.agenticAi.geminiApiKey | quote }}
  {{- end }}
